apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceone
  template:
    metadata:
      labels:
        app: serviceone
    spec:
      containers:
        - name: serviceone
          image: registry.kapitalbank.az/sre/serviceone:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: serviceone
spec:
  selector:
    app: serviceone
  ports:
    - name: http
      port: 80
      targetPort: 8080
